apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-blogs
  labels:
    app: web-blogs
    env: test
  namespace: platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-blogs
  revisionHistoryLimit: 1
  template:
    metadata:
      name: web-blogs
      labels:
        env: test
        app: web-blogs
    spec:
      imagePullSecrets:
        - name: taras
      containers:
      - name: web-blogs
        image: steblynskyi/web-blogs:v0.1.3
        imagePullPolicy: Always
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /web/health/live
        #     port: http
        #     scheme: HTTP
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 5
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: http
        env:
        - name: GMAIL_SMTP_ADDRESS
          valueFrom:
            secretKeyRef:
              name: gmail-smtp-secret
              key: GMAIL_SMTP_ADDRESS
        - name: GMAIL_SMTP_EMAIL
          valueFrom:
            secretKeyRef:
              name: gmail-smtp-secret
              key: GMAIL_SMTP_EMAIL
        - name: GMAIL_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gmail-smtp-secret
              key: GMAIL_SMTP_PASSWORD
        - name: FLASK_KEY
          value: "1234"
        - name: DB_HOST
          value: "postgresql.postgresql.svc.cluster.local"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: web-blogs
  namespace: platform
  labels:
    domain: web-blogs.test
spec:
  selector:
    app: web-blogs
    env: test
  ports:
  - port: 8080
    name: tcp
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-blogs
  namespace: platform
spec:
  maxReplicas: 2
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-blogs
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 220Mi