apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        hosts {
           192.168.65.254 host.minikube.internal
           fallthrough
        }
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
    test:53 {
            errors
            cache 30
            forward . 192.168.49.2
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-18T22:22:32Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "860"
  uid: 3ba0a9eb-d259-457c-9e85-d7a7b59aa1ab